# -*- coding: utf-8 -*-
"""requirements

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7jQ94_Bsy8_zyA8vJwCxQTpxwpqXEdk
"""

pip install streamlit

pip install plotly

pip install pandas

pip install matplotlib

pip install numpy